table olist_customers_dataset
	lineageTag: a31052be-0b56-4163-b043-ed482220bcc4

	measure 'Orders per Category' = ```
			
			CALCULATE(
			    DISTINCTCOUNT('olist_order_items_dataset'[order_id]),
			    KEEPFILTERS('olist_products_dataset') 
			)
			
			```
		formatString: 0
		lineageTag: 6db94717-6033-4c37-b6fd-3a5f73e299a4

	measure 'Order Dibatalkan' = DISTINCTCOUNT(olist_orders_dataset[order_id]) - DISTINCTCOUNT(olist_order_items_dataset[order_id])
		formatString: 0
		lineageTag: e8dde6b9-2f4f-4a8f-8d1c-1ed19a96bdf9

	measure 'Orders by Month' = ```
			
			DISTINCTCOUNT('olist_orders_dataset'[order_id])
			
			```
		formatString: 0
		lineageTag: d0bef9a1-df27-4623-9b64-79971f8b11d4

	column customer_id
		dataType: string
		lineageTag: 118e1b48-8586-4921-9c16-8824058d6086
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 45bf4be7-326e-433f-8dc1-c841429f0aa8
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 6dea23cc-380a-4ec2-a234-2a3762f4fb80
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 2a9ff167-7516-4310-883a-955e397609a8
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: cb604637-9ae4-433e-b19a-c9e92ebe812c
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition olist_customers_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Download\Olist E-Commerce Dataset\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

