table olist_products_dataset
	lineageTag: 415f17de-ed3f-4ba2-991c-24dfd800d91f

	column product_id
		dataType: string
		lineageTag: ee50e7ff-34d7-4726-a5fc-f8bf624fd6d1
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: int64
		formatString: 0
		lineageTag: b9d3fb24-872e-457e-af9a-6df735d5fbfb
		summarizeBy: sum
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: int64
		formatString: 0
		lineageTag: 4d19a39a-e0e1-413c-b5b8-ce7570c70f9d
		summarizeBy: sum
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: 0858250d-2825-4f6e-a139-d20485582fab
		summarizeBy: sum
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: d7812c4f-31b5-44b7-abe1-2ae54f9a0a6a
		summarizeBy: sum
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 2075459b-6359-4fbc-a733-9e3cdd1c2e7a
		summarizeBy: sum
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: 5dbcfb97-3625-4156-a795-c01be4c7c075
		summarizeBy: sum
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: a1e58104-aff7-40f8-bb99-40d1ef26489a
		summarizeBy: sum
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column 'product_category_name_translation.product_category_name_english'
		dataType: string
		lineageTag: 3cfe6bcf-f2d4-45b7-aed8-fe04e9a36069
		summarizeBy: none
		sourceColumn: product_category_name_translation.product_category_name_english

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 70499416-da15-4d7f-91f5-339d6dc38424
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	partition olist_products_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Download\Olist E-Commerce Dataset\olist_products_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"product_category_name"}, product_category_name_translation, {"product_category_name"}, "product_category_name_translation", JoinKind.LeftOuter),
				    #"Expanded product_category_name_translation" = Table.ExpandTableColumn(#"Merged Queries", "product_category_name_translation", {"product_category_name", "product_category_name_english"}, {"product_category_name_translation.product_category_name", "product_category_name_translation.product_category_name_english"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded product_category_name_translation",{"product_category_name_translation.product_category_name"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"product_id", "product_category_name", "product_category_name_translation.product_category_name_english", "product_name_lenght", "product_description_lenght", "product_photos_qty", "product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","_"," ",Replacer.ReplaceText,{"product_category_name_translation.product_category_name_english"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Replaced Value", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Blank Rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Blank Rows2" = Table.SelectRows(#"Removed Blank Rows1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Blank Rows2",null,"unknow category",Replacer.ReplaceValue,{"product_category_name_translation.product_category_name_english"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value1",{{"product_category_name_translation.product_category_name_english", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

